spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

  data.mongodb:
    host: localhost
    port: 27017
    database: prices

  task.scheduling.pool:
    size: 4

  headless: hello

---
spring:
  profiles: prod

  data.mongodb:
    host: mongodb
    port: 27017
    database: prices

  task.scheduling.pool:
      size: 4
---

spring:
  profiles: raspberry

  data.mongodb:
    host: mongodb
    port: 27017
    database: prices

  task.scheduling.pool:
      size: 4